spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080